# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab68c393b241133cac330fe3d4bd799bc1954a5301ac0829632cbdf2d55aefaeb61660a6a16a9efd0dbe4ca1a0e28d07988b29a8f02a58576615be7b131e63c9

test:
  secret_key_base: 9deaa0d3d427ebe65177680b0ff63950e10fd58cb3d162409943f8f3647f72478b5595daa5e84c72360fc2c1cd7a273d7d3f1d4f6d138d7b4417cdda18dfa2c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
